export const metadata = {
  title: "Blog — Web Development Insights | Sajawal Raza Mandra",
  description: "Expert insights on React.js, Next.js, MERN Stack, Shopify, SEO & Freelancing by Sajawal Raza Mandra — Professional Web Developer Pakistan with 40+ projects delivered worldwide.",
keywords: [
  // ── PERSONAL & BRAND ──────────────────────────────
  'sajawal raza mandra',
  'sajawal raza web developer',
  'sajawal mandra developer',
  'sajawal raza mandra blog',
  'sajawal raza portfolio',

  // ── PAKISTAN LOCATION-BASED ───────────────────────
  'web developer pakistan',
  'web developer karachi',
  'web design karachi',
  'react developer pakistan',
  'nextjs developer pakistan',
  'freelance web developer pakistan',
  'mern stack developer pakistan',
  'frontend developer pakistan',
  'shopify developer pakistan',
  'hire web developer pakistan',
  'portfolio web developer pakistan',
  'full stack developer pakistan',
  'nodejs developer pakistan',
  'mongodb developer pakistan',

  // ── WORLDWIDE — HIGH VOLUME (Hire Intent) ─────────
  'hire web developer',
  'hire react developer',
  'hire full stack developer',
  'hire mern stack developer',
  'hire nextjs developer',
  'hire shopify developer',
  'freelance web developer',
  'web developer for hire',
  'remote web developer',
  'dedicated web developer',
  'remote react developer',
  'remote full stack developer',

  // ── WORLDWIDE — SERVICES ──────────────────────────
  'full stack web developer',
  'mern stack development',
  'react developer',
  'reactjs development services',
  'react frontend developer',
  'custom react application development',
  'nextjs development services',
  'nodejs backend developer',
  'express js developer',
  'mongodb developer',
  'rest api developer',
  'shopify store development',
  'custom ecommerce development',
  'ecommerce website development',
  'custom web application development',
  'responsive web design',
  'web performance optimization',

  // ── WORLDWIDE — BLOG & TUTORIALS ─────────────────
  'web development blog',
  'react.js tutorial',
  'next.js guide',
  'mern stack tutorial',
  'shopify store setup guide',
  'freelancing tips for developers',
  'core web vitals guide',
  'website speed optimization',
  'tailwind css tips',
  'seo for web developers',
  'google analytics 4 setup',
  'rest api integration nextjs',
  'mongodb tutorial beginners',
  'wordpress vs nextjs',
  'react vs nextjs 2026',
  'how to build portfolio website',
  'how to get freelance clients',
  'developer portfolio tips',
  'how to start online store',

  // ── PAKISTAN — BLOG SPECIFIC ──────────────────────
  'web development blog pakistan',
  'next.js guide pakistan',
  'mern stack pakistan',
  'shopify development pakistan',
  'freelancing pakistan',
  'fiverr pakistan freelancer',
  'freelancing payments pakistan',
  'payoneer pakistan freelancer',
  'seo guide pakistani websites',
  'website cost pakistan 2026',
  'ecommerce store pakistan',
  'jazzcash easypaisa shopify',
  'cod shopify pakistan',

  // ── TECH STACK KEYWORDS ───────────────────────────
  'react.js developer 2026',
  'next.js app router seo',
  'mern stack scalable apps',
  'full stack javascript developer',
  'saas web application developer',
  'mvp development services',
  'startup web developer',
  'landing page developer',
],

export default function BlogLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}