export const posts = [
  {
    slug: "react-vs-nextjs-2026",
    title: "React.js vs Next.js — What Should You Use in 2026?",
    date: "May 2026",
    readTime: "8 min read",
    category: "REACT & NEXT.JS",
    excerpt: "Performance, SEO, scalability and developer experience — complete breakdown after 40+ real-world projects for Pakistani developers and freelancers.",
    tags: ["SSR", "SEO"],
  },
  {
    slug: "how-to-build-shopify-store-pakistani-brands-2026",
    title: "How to Build a Shopify Store for Pakistani Brands in 2026",
    date: "May 2026",
    readTime: "6 min read",
    category: "E-COMMERCE",
    excerpt: "Complete 2-day workflow — products, checkout, COD, JazzCash, EasyPaisa setup — from a developer who built 10+ Shopify stores for local Pakistani clients.",
    tags: ["E-Commerce", "COD"],
  },
  {
    slug: "mern-stack-2026-worth-learning-pakistan",
    title: "MERN Stack in 2026 — Still Worth Learning in Pakistan?",
    date: "April 2026",
    readTime: "10 min read",
    category: "MERN",
    excerpt: "MongoDB, Express, React, Node — why MERN still dominates Pakistani freelancing and startup development despite newer alternatives like T3 Stack and Bun.",
    tags: ["MongoDB", "Node.js"],
  },
  {
    slug: "how-to-land-fiverr-client-pakistan",
    title: "How to Land Your First Freelance Client on Fiverr Pakistan",
    date: "April 2026",
    readTime: "7 min read",
    category: "FREELANCING",
    excerpt: "Exact strategy for getting first orders with zero reviews — Fiverr profile optimization, gig SEO, proposal writing and psychology tips that actually work in 2026.",
    tags: ["Fiverr", "Profile"],
  },
  {
    slug: "website-speed-core-web-vitals-guide-2026",
    title: "Website Speed & Core Web Vitals Complete Guide 2026",
    date: "April 2026",
    readTime: "9 min read",
    category: "PERFORMANCE",
    excerpt: "LCP, INP, CLS explained with real fixes — how to score 90+ on Google PageSpeed, rank higher in search results and reduce bounce rate significantly.",
    tags: ["LCP", "CLS"],
  },
  {
    slug: "tailwind-css-tricks-ui-design-2026",
    title: "10 Tailwind CSS Tricks That Level Up Your UI Design in 2026",
    date: "March 2026",
    readTime: "5 min read",
    category: "TAILWIND",
    excerpt: "Glassmorphism, gradient text, group hover, clamp fonts, skeleton loaders — practical Tailwind tricks for premium-looking interfaces that impress clients.",
    tags: ["CSS", "Animation"],
  },
  {
    slug: "complete-seo-guide-pakistani-websites-2026",
    title: "Complete SEO Guide for Pakistani Websites 2026 — Rank on Google",
    date: "March 2026",
    readTime: "11 min read",
    category: "SEO",
    excerpt: "How to rank your Pakistani business website on Google — keyword research, on-page SEO, Google Search Console, backlinks, Google Business Profile and local SEO tactics.",
    tags: ["Keywords", "On-Page"],
  },
  {
    slug: "website-banana-ka-kharcha-pakistan-2026",
    title: "Website Banana Ka Kharcha Pakistan 2026 — Real Pricing Guide",
    date: "March 2026",
    readTime: "6 min read",
    category: "PAKISTAN",
    excerpt: "Landing page, business website, e-commerce, full-stack app — Pakistan mein honest pricing breakdown 2026 mein. Cheap vs quality difference explained.",
    tags: ["Budget", "Pakistan"],
  },
  {
    slug: "wordpress-vs-nextjs-pakistani-businesses",
    title: "WordPress vs Next.js — Which is Better for Pakistani Businesses?",
    date: "February 2026",
    readTime: "8 min read",
    category: "COMPARISON",
    excerpt: "Speed, SEO, security, cost and maintenance — honest comparison for Pakistani business owners and freelancers deciding which platform to choose in 2026.",
    tags: ["WordPress", "Speed"],
  },
  {
    slug: "how-to-receive-freelancing-payments-pakistan-2026",
    title: "How to Receive Freelancing Payments in Pakistan 2026",
    date: "February 2026",
    readTime: "7 min read",
    category: "FREELANCING",
    excerpt: "Payoneer, Bank Alfalah, Wise, JazzCash — which payment method is best for Pakistani freelancers in 2026, with FBR tax implications explained clearly.",
    tags: ["Payoneer", "Tax"],
  },
  {
    slug: "rest-api-integration-nextjs-complete-guide",
    title: "REST API Integration in Next.js — Complete Guide with Real Examples",
    date: "January 2026",
    readTime: "9 min read",
    category: "API",
    excerpt: "Connecting Next.js apps to payment gateways, WhatsApp API, Google Maps, email services and custom backends with proper authentication and error handling.",
    tags: ["REST", "JazzCash"],
  },
  {
    slug: "how-to-build-portfolio-website-gets-clients-2026",
    title: "How to Build a Portfolio Website That Gets You Clients in 2026",
    date: "January 2026",
    readTime: "8 min read",
    category: "PORTFOLIO",
    excerpt: "What every developer portfolio must have — projects with live links, case studies, SEO, Google ranking for your name and psychological trust factors.",
    tags: ["Portfolio", "Career"],
  },
  {
    slug: "mongodb-complete-guide-pakistani-developers",
    title: "MongoDB Complete Guide for Pakistani Developers — Beginners to Pro",
    date: "December 2025",
    readTime: "10 min read",
    category: "DATABASE",
    excerpt: "Collections, documents, Mongoose, Atlas cloud database — everything a MERN stack developer needs to know about MongoDB with practical Pakistani project examples.",
    tags: ["Database", "Mongoose"],
  },
  {
    slug: "how-to-start-online-store-pakistan-2026",
    title: "How to Start an Online Store in Pakistan 2026 — Complete Guide",
    date: "December 2025",
    readTime: "7 min read",
    category: "E-COMMERCE",
    excerpt: "Shopify vs custom Next.js store — which is better, true costs, payment methods (COD, JazzCash), and how to get your first online sale in Pakistan.",
    tags: ["Shopify", "COD"],
  },
  {
    slug: "how-to-setup-google-analytics-4-website-2026",
    title: "How to Set Up Google Analytics 4 on Your Website — 2026 Guide",
    date: "November 2025",
    readTime: "6 min read",
    category: "ANALYTICS",
    excerpt: "Track visitors, bounce rate, traffic sources — complete guide to install GA4 on Next.js, WordPress and any website, with key metrics Pakistani businesses should monitor.",
    tags: ["GA4", "Traffic"],
  },
]

export function getPostBySlug(slug) {
  return posts.find((p) => p.slug === slug)
}

export function getAllSlugs() {
  return posts.map((p) => p.slug)
}